site_name: Clinicians Who Code - The Opinionated Handbook

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - navigation.top
  #  - toc.integrate

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

  favicon: img/cwc-logo-white.svg
  logo: img/cwc-logo-white.svg

plugins:
  - search

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - toc:
      permalink: true

nav:
  - Home: home.md
  - Handbook:
      - Foreword: foreword.md
      - Introduction: introduction.md
      - Basics:
          - Orientation: basics/orientation.md
          - Glossary: basics/glossary.md
          - Mantras: basics/mantras.md
      - Getting Started:
          - Which Language?: getting-started/what-language.md
          - Why Python?: getting-started/why-python.md
          - Learning Python: getting-started/learning-python.md
          - Web Frameworks: getting-started/web-frameworks.md
          - Learning Django: getting-started/learning-django.md
  - About: about.md
  - Donate: donate.md

copyright: Copyright &copy; 2021 Dr Marcus Baw
repo_url: https://github.com/pacharanero/clinicians-who-code-the-opinionated-handbook

extra_css:
  - stylesheets/extra.css
